In [1]:
import numpy as np

In [2]:
my_list =[1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,5, 15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.555643344331204

In [19]:
np.random.rand(5)

array([0.65164151, 0.53029458, 0.71624956, 0.25494272, 0.20749399])

In [20]:
np.random.rand(4,3)

array([[0.69411371, 0.82790743, 0.25781617],
       [0.64900693, 0.91307302, 0.8519171 ],
       [0.61033068, 0.40565853, 0.72004414],
       [0.16104156, 0.5862042 , 0.06623379]])

In [21]:
np.ramdom.randn(2)

AttributeError: module 'numpy' has no attribute 'ramdom'

In [ ]:
np.random.randn(2)

array([0.86015689, 0.15307982])

In [ ]:
np.random.randn(5)

array([-0.2678991 ,  0.64314602, -0.03800705, -1.29718581, -0.29970477])

In [ ]:
np.random.randn(5,6)

array([[ 8.03760493e-01, -1.07823823e+00, -1.14156031e+00,
         9.12876885e-01,  3.56389149e-01,  3.59500503e-01],
       [ 1.37561500e+00, -5.46736334e-01, -6.82704045e-01,
        -7.85886746e-01,  8.44019870e-01, -1.06273821e+00],
       [ 2.07710104e+00,  5.96313760e-01, -7.50604077e-01,
        -5.44215064e-01,  7.15143941e-01, -1.42302325e-01],
       [ 4.72663863e-01,  5.90130722e-01, -4.90306159e-01,
         1.62655904e-01,  1.01975433e+00, -7.05617124e-01],
       [-1.17929922e+00, -2.05290170e-03, -8.06924705e-01,
        -1.84468827e-01,  4.14655869e-01, -7.69039137e-01]])

In [ ]:
np.random.randint(1,100,10)

array([43, 53, 92, 21, 36, 81, 40,  7, 92,  5])

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
randomArray = np.random.randint(0,100,10)

In [ ]:
randomArray

array([57,  4, 29, 14, 59, 24, 29, 58, 68, 33])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [ ]:
randomArray

array([57,  4, 29, 14, 59, 24, 29, 58, 68, 33])

In [ ]:
randomArray.max()

68

In [ ]:
randomArray.min()

4

In [ ]:
randomArray.argmax()

8

In [ ]:
randomArray.argmin()

1

In [ ]:
randomArray.shape

(10,)

In [ ]:
randomArray.reshape(2,5)

array([[57,  4, 29, 14, 59],
       [24, 29, 58, 68, 33]])

In [ ]:
randomArray.dtype

dtype('int32')